Repository flowacademyhu/piac-app, pull requests merged in 2021-11, with the labels that each got.

#102 Bugfix logo images
  frontend/src/components/MarketInfo.js
  frontend/src/components/VendorCard.js
  frontend/src/components/VendorHeader.js
  frontend/src/styles/MarketCard.css
  frontend/src/styles/VendorCard.css
  frontend/src/styles/vendor-header.css
Labels: bug

#100 Bugfix footer mouse hover
  frontend/src/components/Footer.js
  frontend/src/components/FooterButton.js
Labels: bug

#96 fixed facebook and instagram link in contact list
  frontend/src/components/VendorContacts.js
Labels: bug

#86 fixing market card, when zero the vendors
  frontend/src/components/MarketCard.js
Labels: bug

#94 Bugfix in progress bar flashing in market page
  frontend/src/components/VendorlistUploadInProgress.js
  frontend/src/pages/VendorsByMarketPage.js
Labels: bug

#103 Bugfix header footer height
  frontend/src/components/Footer.css
  frontend/src/components/Header.css
  frontend/src/components/HeaderWithMarket.js
  frontend/src/components/MarketInfo.js
  frontend/src/components/VendorlistUploadInProgress.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/MarketCard.css
  frontend/src/styles/MarketCardList.css
  frontend/src/styles/VendorlistUploadInProgress.css
Labels: bug

#99 Bugfix vertical scrolling
  frontend/src/components/App.js
  frontend/src/components/Footer.css
  frontend/src/components/Header.css
  frontend/src/components/HeaderWithMarket.js
  frontend/src/styles/App.css
  frontend/src/styles/HeaderWithMarket.css
  frontend/src/styles/MarketCardList.css
  frontend/src/styles/VendorlistUploadInProgress.css
  frontend/src/styles/index.css
  frontend/src/styles/vendor-introduction.css
Labels: bug

#97 Enhancement reversing marketlist order and removing outdated markets
  backend/src/main/java/org/example/spring/boot/skeleton/controller/MarketController.java
  backend/src/main/java/org/example/spring/boot/skeleton/helper/StartUpRunner.java
  backend/src/main/java/org/example/spring/boot/skeleton/repositories/MarketRepository.java
  backend/src/main/java/org/example/spring/boot/skeleton/services/MarketService.java
  frontend/src/components/MarketCardList.js
  frontend/src/components/Service.js
Labels: enhancement

#125 Delete helper directory
  backend/src/main/java/org/example/spring/boot/skeleton/helper/StartUpRunner.java
Labels: bug

#119 Fixed Footer.css
  frontend/package-lock.json
  frontend/src/components/Footer.css
Labels: bug

#118 Bugfix footer flash
  frontend/src/components/Footer.js
  frontend/src/components/MarketCard.js
  frontend/src/components/MarketInfo.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/MarketCard.css
Labels: bug

#124 product-margin changed
  frontend/src/components/Products.css
Labels: enhancement

#126 Small changes for market and vendor cards
  frontend/src/components/HeaderWithMarket.js
  frontend/src/styles/MarketCard.css
  frontend/src/styles/MarketCardList.css
  frontend/src/styles/VendorCard.css
Labels: enhancement

#111 fontWeight changed in vendorProfile
  frontend/src/components/Products.css
  frontend/src/styles/VendorContacts.css
  frontend/src/styles/vendor-introduction.css
Labels: bug

#123 Feature vendor introduction
  backend/src/main/java/org/flowacademy/hu/market/app/entities/Vendor.java
  backend/src/main/java/org/flowacademy/hu/market/app/model/VendorDTO.java
  frontend/src/styles/vendor-introduction.css
Labels: enhancement

#107 Frontend - redirect market/vendor pages
  frontend/src/components/App.js
  frontend/src/pages/VendorProfilePage.js
  frontend/src/pages/VendorsByMarketPage.js
Labels: bug

#142 theme color changed to lightgrey
  frontend/public/index.html
Labels: bug

#130 change market opening and closing dates to be different for testing
  backend/src/main/java/org/flowacademy/hu/market/app/services/MarketService.java
Labels: technical

#138 Feature vendor profile filter markets
  backend/src/main/java/org/flowacademy/hu/market/app/controller/VendorController.java
  backend/src/main/java/org/flowacademy/hu/market/app/repositories/MarketRepository.java
  backend/src/main/java/org/flowacademy/hu/market/app/services/MarketService.java
Labels: enhancement, backend

#154 Bugifx vendor profile page
  backend/src/main/java/org/flowacademy/hu/market/app/services/VendorService.java
  frontend/src/components/VendorContacts.js
Labels: bug

#155 text-alignment-fix
  frontend/src/components/VendorlistUploadInProgress.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/VendorlistUploadInProgress.css
Labels: bug

#157 Feature get markets on vendor profile
  frontend/src/components/Service.js
  frontend/src/components/VendorInfoNav.css
  frontend/src/components/VendorInfoNav.js
Labels: enhancement

#163 sorting by name function added to vendor list of one market
  frontend/src/components/SortByName.js
  frontend/src/components/VendorListOfOneMarket.js
  frontend/src/styles/VendorCard.css
Labels: bug

#153 Change logo border color logo size and add placeholder logo
  frontend/src/components/MarketInfo.js
  frontend/src/components/VendorCard.js
  frontend/src/components/VendorHeader.js
  frontend/src/img/defaultMarketImage.png
  frontend/src/img/defaultVendorImage.png
  frontend/src/styles/MarketCard.css
  frontend/src/styles/VendorCard.css
  frontend/src/styles/vendor-header.css
Labels: enhancement

#176 Vendor Profile inner routes removed
  frontend/src/components/App.js
  frontend/src/components/VendorInfoNav.css
  frontend/src/components/VendorInfoNav.js
  frontend/src/components/VendorProfileInfo.js
  frontend/src/components/VendorProfileMarkets.js
  frontend/src/pages/VendorProfilePage.js
Labels: enhancement

#187 Redesign vendor profile header
  frontend/src/components/App.js
  frontend/src/components/Payment.js
  frontend/src/components/VendorHeader.js
  frontend/src/components/VendorInfoNav.css
  frontend/src/components/VendorInfoNav.js
  frontend/src/components/VendorProfileInfo.js
  frontend/src/components/VendorProfileMarkets.js
  frontend/src/pages/VendorProfilePage.js
  frontend/src/styles/payment.css
  frontend/src/styles/vendor-header.css
Labels: enhancement

#182 VendorProfile - redesigned product section
  frontend/src/components/ProductList.js
  frontend/src/components/Products.css
  frontend/src/components/Products.js
  frontend/src/icons/tag.svg
Labels: enhancement

#188 Create market and vendor tables for admin site
  admin/package-lock.json
  admin/package.json
  admin/public/index.html
  admin/src/App.js
  admin/src/App.test.js
  admin/src/components/MarketTable.js
  admin/src/components/Menu.js
  admin/src/components/Service.js
  admin/src/components/VendorTable.js
  admin/src/logo.svg
  admin/src/pages/MarketTablePage.js
  admin/src/pages/VendorTablePage.js
  admin/src/setupTests.js
Labels: task

#174 Implement error pages
  frontend/src/components/ErrorBody.js
  frontend/src/components/HeaderWithMarket.js
  frontend/src/components/MarketCardList.js
  frontend/src/components/Service.js
  frontend/src/components/VendorCardList.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/Error.css
  frontend/src/styles/VendorContacts.css
Labels: task

#165 admin endpoints for add, update, delete vendors and markets fixed
  backend/src/main/java/org/flowacademy/hu/market/app/entities/Vendor.java
  backend/src/main/java/org/flowacademy/hu/market/app/repositories/MarketRepository.java
  backend/src/main/java/org/flowacademy/hu/market/app/services/AuthenticationService.java
  backend/src/main/java/org/flowacademy/hu/market/app/services/MarketService.java
  backend/src/main/java/org/flowacademy/hu/market/app/services/VendorService.java
Labels: backend

#195 Redesign fully market card
  frontend/src/components/HeaderWithMarket.js
  frontend/src/components/MarketCard.js
  frontend/src/components/MarketInfoList.js
  frontend/src/styles/MarketInfoList.css
Labels: enhancement

#189 Feature search vendor
  .github/workflows/main.yml
  backend/src/main/java/org/flowacademy/hu/market/app/model/SimpleVendorDTO.java
  backend/src/main/java/org/flowacademy/hu/market/app/services/VendorService.java
  frontend/src/components/SearchArea.js
  frontend/src/components/VendorCardList.js
  frontend/src/components/VendorListOfOneMarket.js
  frontend/src/functions/filteredArrayByKeyword.js
  frontend/src/functions/matchFormat.js
  frontend/src/functions/textIsIncludesKeyword.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/Search.css
  frontend/src/tests/filteredArrayByKeyword.test.js
  frontend/src/tests/ignoreAccents.test.js
  frontend/src/tests/textIsIncludesKeyword.test.js
Labels: task

#207 product bar not showing when the product list zero
  frontend/src/components/VendorProfileInfo.js
Labels: bug

#219 default pictures replaced
  frontend/src/icons/navigation/defaultMarketImage.png
  frontend/src/icons/navigation/defaultVendorImage.png
Labels: enhancement

#220 empty-page-message css class changed, text changed
  frontend/src/components/VendorProfileMarkets.js
  frontend/src/styles/VendorInfoNav.css
Labels: enhancement

#221 delete border attributes from vendorLogo class
  frontend/src/styles/VendorCard.css
Labels: enhancement

#212 fixed header on VendorsByMarketPage
  frontend/src/styles/MarketCard.css
Labels: bug

#222 Bugfix vendor list sorting
  frontend/src/components/SortByName.js
  frontend/src/components/VendorCardList.js
Labels: bug

#224 text align center added for vendor name and vendor intro
  frontend/src/styles/vendor-header.css
Labels: bug

#230 A "Kikkel találkozhatsz?" felirat betöltéskor felvillan csak, majd nem jelenik meg a megfelelő helyen
  frontend/src/components/VendorlistUploadInProgress.js
  frontend/src/pages/VendorsByMarketPage.js
  frontend/src/styles/VendorlistUploadInProgress.css
Labels: bug

#229 match format function removed, and replaced with only accented letter…
  frontend/src/components/SortByName.js
  frontend/src/tests/sortByName.test.js
Labels: bug

#231 add missing period at the end of the empty page message
  frontend/src/components/VendorProfileMarkets.js
Labels: bug

#203 Add delete functionality to market and vendor table delete buttons
  admin/src/components/DeleteEntity.js
  admin/src/components/MarketTable.js
  admin/src/components/Service.js
  admin/src/components/VendorTable.js
Labels: task

#248 Technical 233
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/ErrorBody.css
  frontend/src/components/ErrorBody.js
  frontend/src/components/SearchArea.css
  frontend/src/components/SearchArea.js
  frontend/src/header/Header.css
  frontend/src/header/Header.js
  frontend/src/market/MarketCard.js
  frontend/src/market/MarketInfoList.css
  frontend/src/market/MarketInfoList.js
  frontend/src/market/list/MarketCardList.js
  frontend/src/market/profile/HeaderWithMarket.js
  frontend/src/market/profile/MarketCard.css
  frontend/src/market/profile/MarketInfo.js
  frontend/src/market/profile/VendorListOfOneMarket.js
  frontend/src/market/profile/VendorlistUploadInProgress.css
  frontend/src/market/profile/VendorlistUploadInProgress.js
  frontend/src/market/profile/VendorsByMarketPage.js
  frontend/src/styles/AppStyled.js
  frontend/src/styles/CardList.css
  frontend/src/styles/CardListStyled.js
  frontend/src/vendor/VendorCard.css
  frontend/src/vendor/VendorCard.js
  frontend/src/vendor/list/VendorCardList.js
  frontend/src/vendor/profile/VendorHeader.css
  frontend/src/vendor/profile/VendorHeader.js
  frontend/src/vendor/profile/VendorInfoNav.css
  frontend/src/vendor/profile/VendorIntroduction.css
  frontend/src/vendor/profile/VendorIntroduction.js
  frontend/src/vendor/profile/VendorProfileInfo.js
  frontend/src/vendor/profile/VendorProfileMarkets.js
  frontend/src/vendor/profile/VendorProfilePage.js
  frontend/src/vendor/profile/contacts/VendorContacts.css
  frontend/src/vendor/profile/contacts/VendorContacts.js
  frontend/src/vendor/profile/payment/Payment.js
  frontend/src/vendor/profile/payment/payment.css
  frontend/src/vendor/profile/products/ProductList.js
  frontend/src/vendor/profile/products/Products.css
  frontend/src/vendor/profile/products/Products.js
Labels: technical

#249 site-240 - Check vendor contacts before rendering
  frontend/src/vendor/profile/contacts/VendorContacts.js
Labels: enhancement

#260 Use Yarn for the site
  .github/workflows/main.yml
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/yarn.lock
Labels: technical

#259 Use Yarn for the admin
  .github/workflows/main.yml
  admin/Dockerfile
  admin/package-lock.json
  admin/yarn.lock
Labels: technical

#262 Enhancement 241 make search bar sticky
  frontend/src/components/SearchArea.tsx
Labels: enhancement

#256 Using react-query for APIs
  frontend/Dockerfile
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/market/list/MarketCardList.js
  frontend/src/market/profile/VendorsByMarketPage.js
  frontend/src/vendor/list/VendorCardList.js
  frontend/src/vendor/profile/VendorProfileMarkets.js
  frontend/src/vendor/profile/VendorProfilePage.js
  frontend/yarn.lock
Labels: task

#264 Keresésnél ne zoomoljon bele az oldalba
  frontend/public/index.html
Labels: bug
